config/routes.rb
RorTeacher::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for  :users
  resources   :users
  resources   :courses do
    resources :pages
  end
  resources   :courses_user

  root  'courses#index'
  get   '/',                    to: 'courses#index',      as: 'home'
  get   '/about',               to: 'static_pages#about'
  get   '/contact',             to: 'static_pages#contact'
  post  '/courses_user/start',  to: 'courses_user#start'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :courses_users
  has_many :users, through: :courses_users
  has_many :pages
  has_many :assignments

  validates :name, presence: true
  def is_public?
    public == true
  end
end

app/models/courses_user.rb
class CoursesUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  belongs_to :owner, class_name: User, foreign_key: "owner_id"
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :course

  validates :course_id, presence: true
  validates :name,      presence: true, length: { maximum: 15 }
  validates :content,   length: { maximum: 1000 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses_users
  has_many :courses, through: :courses_users
  validates :first_name, :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  has_attached_file :avatar,
                    :styles => { large: "300x300>", small: "50x50#", thumb: "35x35#" },
                    :default_style => :small,
                    :url  => "/assets/users/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension",
                    :default_url => ActionController::Base.helpers.asset_path('assets/small/missing.png', digest: false)

  validates_attachment_size :avatar, less_than: 5.megabytes
  validates_attachment_content_type :avatar, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, message: 'file type is not allowed (only jpeg/png/gif images)'

  def is_student?
    user_type == "student"
  end

  def is_teacher?
    user_type == "teacher"
  end

  def has_course?(course)
    courses.include?(course)
  end

  def is_admin?
    admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

  def authenticate_admin_user!
    redirect_to new_user_session_path unless current_user.try(:is_admin?)
  end

  def get_viewable_courses
    @viewable_courses = []
    if user_signed_in?
      @viewable_courses = if current_user.is_teacher?
        Course.all
      elsif @user
        @user.courses
      else
        current_user.courses
      end
    end
  end

  protected

  def update_sanitized_params
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:avatar, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :get_viewable_courses
  before_action :find_course, only: [:show, :edit]

  def index
    @courses = Course.all.order( name: :asc )
    @user = current_user
  end

  def show
    @pages = @course.pages
  end

  private

  def find_course
    @course = Course.find(params[:id])
  end

end

app/controllers/courses_user_controller.rb
class CoursesUserController < ApplicationController

  before_action :find_user

  def edit
    @courses = Course.all.order(name: :asc)
  end

  def update
    @courses = Course.where(id: (params[:courses_ids] || [] ).map{ |x, y| y })
    @user.courses = @courses
    redirect_to @user
  end

  def start
    @course = Course.find(params[:course_id])
    @user.courses << @course
    redirect_to @course
  end

  private

    def find_user
      @user = User.find(params[:id] || params[:user_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_course
  before_action :find_page, only: [:show, :edit]

  def new
    @page = @course.pages.new
  end

  def create
    @page = @course.pages.new(page_params)
    if @page.save
      flash[:success] = "Page was successfully created"
      redirect_to course_page_path(@course, @page)
    else
      render 'new'
    end
  end

  def update
    @page = @course.pages.where(id: (params[:id])).first
    @page.update_attributes(page_params)
    if @page.save
      flash[:success] = "Contect was successfully updated"
      redirect_to course_page_path(@course, @page)
    else
      render 'edit'
    end
  end

  private

  def page_params
    params.require(:page).permit(:id, :course_id, :name, :content)
  end

  def find_course
    @course = Course.find(params[:course_id])
  end

  def find_page
    @page = Page.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  require 'ffaker'

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :show]
  before_action :get_viewable_courses

  def index
    @students = User.where(user_type: "student").paginate(:page => params[:page], :per_page => 15).order(last_name: :asc)
  end

  def show
    @user = User.find(params[:id])
    @courses = @user.courses.order(name: :asc)
  end

  private

  def signed_in_user
    redirect_to root_url unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
  # Returns the full name for a user.
  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end
end

app/views/courses/index.html.erb
<div>
  <h1>Welcome to the RoR Teacher App</h1>

  <h2>
    This is the home page for the RoR-teacher application.
  </h2>
</div>
<ul class = "courses">
  <%= render 'users/courses' %>
</ul>

app/views/courses/show.html.erb
<div class="row">
  <div class="span8 offset2">
    <h1><%= @course.name %></h1>
  </div>
</div>

<ul class = "courses">
  <% @pages.each do |page| %>
    <li><%= page.name %>
      <%= link_to 'View page', course_page_path(params[:id], page.id), class: :assign %>
    </li>
  <% end %>
</ul>
<% if current_user.is_teacher? %>
  <p>
    <%= link_to '<i class="icon-plus"></i> Add page'.html_safe, new_course_page_path(@course.id), class: "btn btn-large" %>
  </p>
<% end %>

app/views/courses_user/_user.html.erb
<li id = "<%= "user_row_#{course.id}" %>">
  <%= check_box_tag "courses_ids[#{course.id}]", course.id, @user.has_course?(course) %>
  <%= label_tag "courses_ids[#{course.id}]", course.name %>
</li>

app/views/courses_user/edit.html.erb
<h1>
  <%= image_tag @user.avatar.url(:small) %>
  <%= full_name(@user) %>
</h1>

<ul class = "courses_user">
  <%= form_tag courses_user_path, :method => :patch do %>
    <%= hidden_field_tag "user_id", @user.id %>
    <% for course in @courses %>
      <%= render partial: 'user', locals: { course: course } %>
    <% end %>
    <%= submit_tag "Mark as Complete" %>
  <% end %>
</ul>

app/views/courses_user/new.html.erb
<ul class = "courses">
  <%= form_tag courses_user_index_path, method: :post do %>
    <%= hidden_field_tag "user_id", @user.id %>
    <% for course in @courses %>
      <%= render partial: 'user', locals: { course: course } %>
    <% end %>
    <%= submit_tag "Mark as Complete" %>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "RoR Teacher", home_path, id: "logo" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Home", home_path %></li>
          <li class="active"><%= link_to "Users", users_path if user_signed_in? %></li>
          <li class="active"><%= link_to "About", about_path %></li>
          <li class="active"><%= link_to "Contact", contact_path%></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <li><%= link_to "My courses", current_user unless current_user.is_admin? %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR Teacher</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/edit.html.erb
<div class="row">
  <div class="span8 offset2">
    <h1><%= @course.name %></h1>
  </div>
  <div class="span8 offset2">
    <h2><%= @page.name %></h2>
  </div>
</div>

<div class="row">
  <%= form_for @page, url: course_page_path(params[:course_id], params[:id]) do |f| %>
    <%= cktext_area :page, :content %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  <%#<textarea class="ckeditor" name="editor1"></textarea>%>
</div>

app/views/pages/new.html.erb
<div class="row">
  <div class="span8 offset2">
    <h1><%= @course.name %></h1>
  </div>
</div>

<%= form_for @page, url: course_pages_path(params[:course_id], params[:id]) do |f| %>
  <div class="field">
    <%= f.label :name, 'Input name for new page' %>
    <%= f.text_field :name, placeholder: 'Enter page name...' %>
  </div>
<% end %>

app/views/pages/show.html.erb
<div class="row">
  <div class="span8 offset2">
    <h1><%= @course.name %></h1>
  </div>
  <div class="span8 offset2">
    <h2><%= @page.name %></h2>
  </div>
  <div class="span2">
    <%= link_to 'Edit page', edit_course_page_path(@course, @page), class: "assign" %>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= @page.content %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>
  <%= Faker::Lorem.paragraph %>
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  <%= Faker::Lorem.paragraph %>
</p>

app/views/users/_courses.html.erb
<ul class = "courses">
  <% @courses.each do |course| %>
    <li><%= course.name %>
      <% if user_signed_in? %>
        <% if @viewable_courses.include?(course) %>
          <%= link_to 'View course', course_path(course.id), class: :assign %>
        <% else %>
          <% if course.is_public? %>
            <%= link_to 'Start course', courses_user_start_path(course_id: course.id, user_id: current_user), method: :post, class: :assign %>
          <% end %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<div class = "users">
  <% @students.each do |student| %>
    <li>
    <%= image_tag student.avatar.url(:thumb) %>
    <%= link_to full_name(student), user_path(student.id) %>
    <% if current_user == student || current_user.is_teacher? %>
      <%= link_to 'Assign course', edit_courses_user_path(student.id), class: "assign" %>
    <% else %>
      <%= link_to 'View profile', user_path(student.id), class: "assign" %>
    <% end %>
    </li>
  <% end %>
</div>
<%= will_paginate @students, class: :"pagination pagination-centered" %>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="span8 offset2">
      <h1>
        <%= image_tag @user.avatar.url(:small) %>
        <%= full_name(@user) %>
      </h1>
    </div>
    <% if @user==current_user || current_user.is_teacher? %>
      <div class="span2">
        <%= link_to 'Assign course', edit_courses_user_path(@user.id), class: "assign" %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <%= render 'courses' %>
  </div>
<% end %>